### ISSUE TITLE
No smoothing mode?

### ISSUE THREAD

**Issue by qrilka** [phaazon/smoothie#11]
I was searching for a library to do smoothing (using kernel smoother) and have found yours but it appears to do only interpolation even with "smooth" in its name, is it just a coincidence?

**Comment by phaazon** [comment]
What do you call kernel smoother? It performs interpolation between two discrete points, yes.

**Comment by qrilka** [comment]
One of techniques for smoothing, see e.g. [wiki](https://en.wikipedia.org/wiki/Kernel_smoother)

**Comment by phaazon** [comment]
Ah! Well, no, smoothie is about interpolation only, not approximing or extracting functions.
