### ISSUE TITLE
Relax lower bound on aeson?

### ISSUE THREAD

**Issue by DanBurton** [phaazon/smoothie#8]
Is there any chance you can relax the lower bound on `aeson` to include `0.8.*`? Are you using any features specific to `aeson-0.9.*`?

**Comment by phaazon** [comment]
Sure, I’m merging your PR – testing the change before, but that should be okay. Thanks!

**Comment by DanBurton** [comment]
Thanks for the quick response! I see the new version has been uploaded.

**Comment by phaazon** [comment]
Yes, it works for all 0.8 version I tested. Thanks for the PR! :)
